name: lint_python
on: push
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black==20.8b1 codespell flake8
      - run: black --check .
      - run: codespell --ignore-words-list="hist,optionn" --quiet-level=2  # --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
