# https://pre-commit.com
# This GitHub Action assumes that the repo contains a valid .pre-commit-config.yaml file.
name: pre-commit, build and test
on: [pull_request, push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/setup-python@v2
      - run: pip install pre-commit
      - run: pre-commit --version
      - run: pre-commit install
      - run: pre-commit run --all-files
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[MongoTrials, SparkTrials, ATPE, dev]'
          pip install pyspark
      - name: Test with pytest - Unit tests
        run: |
          python -m pytest ./hyperopt/tests/unit
      - name: Test spark plugin - pin thread mode
        run: |
          PYSPARK_PIN_THREAD=true pytest hyperopt/tests/integration/test_spark.py
      - name: Test spark plugin - non pin thread mode
        run: |
          PYSPARK_PIN_THREAD=false pytest hyperopt/tests/integration/test_spark.py
