name: Test
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: uv sync --group dev
      - name: Test with pytest - everything - pyspark in pin thread mode
        run: |
          PYSPARK_PIN_THREAD=true uv run pytest
      - name: Test spark plugin - non pin thread mode
        run: |
          PYSPARK_PIN_THREAD=false uv run pytest hyperopt/tests/integration/test_spark.py
